services:
  rwds_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rwds_server
    stop_signal: SIGINT
    ports:
      - '5001:5001'
    networks:
      - app-network

  drv_server:
    image: drv_server
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    volumes:
      - '${USERPROFILE:-$HOME}/Documents/AirSim:/root/Documents/AirSim'  # Assuming your container expects this at /root/Documents/AirSim
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
