#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
runApplication $(getApplication)
runApplication reconstructParMesh -constant
runApplication reconstructPar