#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

## Remove surface and features
#rm -f constant/geometry/motorBike.obj.gz

cleanCase

# Remove C, Cx, Cy, Cz files in all time directories
rm -f [0-9]*/[C]*




#------------------------------------------------------------------------------
