#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. /opt/openfoam10/bin/tools/CleanFunctions

cleanCase
cleanExplicitFeatures

rm -f [0-9]*/[C]*




#------------------------------------------------------------------------------
