#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. /opt/openfoam10/etc/bashrc
. /opt/openfoam10/bin/tools/RunFunctions

runApplication surfaceFeatures

runApplication blockMesh

runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite

runParallel patchSummary
runParallel potentialFoam
runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar
postProcess -func writeCellCentres
# this is a hack to get the cell centres written out, which is needed for the velocity field to coordinate mapping
touch results.foam


#------------------------------------------------------------------------------
